-- --------------------------------------------------------

--
-- Table structure for table `config`
--

CREATE TABLE IF NOT EXISTS `config` (
  `module` varchar(64) NOT NULL,
  `key` varchar(96) NOT NULL,
  `value` mediumtext NOT NULL,
  KEY `module` (`module`),
  KEY `key` (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `config`
--

INSERT INTO `config` (`module`, `key`, `value`) VALUES
('core', 'site-name', 'Talkwork'),
('core', 'sef-urls', 'true'),
('core', 'default-module', 'pages'),
('core', 'default-controller', 'view'),
('core', 'default-params', '1'),
('core', 'default-theme', 'default'),
('core', 'active-plugins', ''),
('core', 'timezone', '-6'),
('core', 'charset', 'UTF-8'),
('core', 'lang', 'en-US'),
('core', 'site-name-in-title', 'first'),
('core', 'title-separator', '||');

-- --------------------------------------------------------

--
-- Table structure for table `pages`
--

CREATE TABLE IF NOT EXISTS `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `name` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

--
-- Dumping data for table `pages`
--

INSERT INTO `pages` (`id`, `slug`, `name`, `content`) VALUES
(1, 'home', 'Welcome!', '<img src="/logo.png" alt="[Talkwork logo]"><br><h2>Welcome!</h2>\r\n<p>Thanks for visiting. <a href="http://sourceforge.net/projects/talkwork/">This SourceForge project</a> is currently in the very early stages of development.</p>\r\n<h2>FAQ</h2>\r\n<ul><li><h3>What is Talkwork?</h3><p>Talkwork is a <a href="http://en.wikipedia.org/wiki/Web_application_framework">web application framework</a> that will come with the necessary components to manage a typical website, making it a <a href="http://en.wikipedia.org/wiki/Content_management_system">CMS</a> as well. It is written in <a href="http://en.wikipedia.org/wiki/PHP">PHP</a> <a href="http://php.net/">5</a>, using <a href="http://en.wikipedia.org/wiki/Object-oriented_programming">object orientation</a> where necessary and helpful. My original notion was to pursue an <a href="http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">MVC</a> <a href="http://en.wikipedia.org/wiki/Architectural_pattern_%28computer_science%29">architectural pattern</a>, but now I''m not so sure what you''d call the code I''ve written so far. My own pattern, maybe &ndash; which is fine with me. My intent behind this project is to make a framework that uses easily-understandable code and is <em>fast</em>, and to make a feature-rich CMS that is easy to use and understand. Another motive of mine is to improve my coding skills by learning as I go. I''ve never undertaken any coding project of this magnitude before, so I know I will learn a lot. As the days go by, I keep encountering circumstances where I just know that if my framework were finished and ready to use, it would be a perfect solution for the given need. So yes, my visions are grandiose, but it doesn''t hurt to dream, does it? ;)</p></li>\r\n<li><h3>What features will Talkwork have?</h3><ul><li>Search-engine-friendly URLs as standard</li><li>Standard modules: static pages (included), blog, and eventually forum and e-commerce</li></ul></li>\r\n<li><h3>Is this site running on Talkwork?</h3><p>Yes! Guess what? I currently have to edit the database with phpMyAdmin everytime I want to modify the content! Isn''t that wonderful?</p></li>\r\n<li><h3>What''s with the weird name?</h3><p>The name was actually generated by <a href="http://wordoid.com/">Wordoid</a> (which I discovered thanks to <a href="http://chris.pirillo.com/how-to-choose-a-good-domain-name/">Chris Pirillo</a>), and I liked it enough to contrive a meaning for it: it is a frame<strong>work</strong> to facilitate communication (or "<strong>talk</strong>").<br>Yeah, I know it''s weak. You got a better idea? <a href="http://garrettw.net/contact.php">Talk to me.</a></p></li>\r\n<li><h3>What''s with the weird logo?</h3><p>It''s meant to look like an inside-out speech bubble. "But why?" you may ask. Because it doesn''t take up the extraneous space that a proper speech bubble would, coming out of the top of that ''w''.</p><q>I''m a programmer, not a graphic artist!</q></li>\r\n<li><h3>Can I help out with development?</h3><p>Sure, I''d <em>love</em> to work with you if you know PHP 5 and MySQL. <a href="http://garrettw.net/contact.php">Shoot me an email.</a></ul>\r\n<br><br><br>\r\n<p style="text-align:center;font-size:small">Talkwork is licensed under <a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="/gplv3-88x31.png" alt="GPL V3" style="border:none"></a> and this site is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" title="This site is covered by a Creative Commons license. You are free to: share, remix - under the following conditions: attribution, noncommercial, share alike"><img src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/80x15.png" alt="Creative Commons License" style="border:none"></a>.</p>\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `plugins`
--

CREATE TABLE IF NOT EXISTS `plugins` (
  `name` varchar(64) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `for-modules` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `configdata` longtext NOT NULL,
  PRIMARY KEY (`name`),
  KEY `active` (`active`),
  KEY `for-modules` (`for-modules`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pwhash1` binary(40) NOT NULL,
  `pwhash2` binary(40) NOT NULL,
  `role` mediumtext NOT NULL,
  `custom-perms` mediumtext NOT NULL,
  `displayname` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `displayname` (`displayname`,`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `pwhash1`, `pwhash2`, `role`, `custom-perms`, `displayname`, `email`)
  VALUES (1, 'admin',
  '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0',
  '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0',
  '', '', 'Admin', 'admin@test.com'
);
